### ISSUE TITLE
可否在你的ubuntu那个安装了里面加上这个

### ISSUE THREAD

**Issue by xizero00** [inkss/markdown#1]
[添加触摸板的手势支持](https://www.maketecheasier.com/add-multitouch-gestures-ubuntu/)

[印象笔记开源客户端](https://github.com/robert7/nixnote2/releases)

有空我再来补充
谢谢啦。

**Comment by inkss** [comment]
触摸板这个我查了一下，这个库好像很久没有更新了而且还有一大堆 issues 存在，找到另外一个我先测试一下。相关链接：[kde5与archlinux环境下配置libinput-gestures多手势操作](https://segmentfault.com/a/1190000011327776)
